title: Katie Shaffer
description: Senior Data Analyst at Scan.com
logo: https://media.licdn.com/dms/image/v2/C5603AQHEBbYVZ6tVOw/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1517464337606?e=1746057600&v=beta&t=Xc1hnuC___pPhS-6MrmlBxBJF8Rtqbx7v8fDm0sdu0U
theme: jekyll-theme-minimal
