title: Katie Shaffer
description: Welcome to my page! I am an experienced data analyst with a specific focus in the healthcare industry. I take a highly collaborative approach to analytics and believe that a solid understanding of the business is crucial in order to provide valuable insights.
#logo: https://media.licdn.com/dms/image/v2/C5603AQHEBbYVZ6tVOw/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1517464337606?e=1746057600&v=beta&t=Xc1hnuC___pPhS-6MrmlBxBJF8Rtqbx7v8fDm0sdu0U
theme: jekyll-theme-minimal
